[tox]
envlist = lint, typecheck, build, py311, py312, py313, py314
requires = tox-uv
skip_missing_interpreters = true
no_package = true

[testenv]
deps = -e .
dependency_groups = test, torch-cpu
allowlist_externals = pytest
commands =
    pytest {posargs}

[testenv:lint]
basepython = python3.11
dependency_groups = test
allowlist_externals =
    ruff
    black
    isort
commands =
    black --check --diff --color .
    isort --check --diff .
    ruff check .

[testenv:typecheck]
basepython = python3.11
dependency_groups = test, torch-cpu
allowlist_externals = mypy
commands =
    mypy .

[testenv:build]
basepython = python3.11
allowlist_externals = uv
commands =
    uv build

